### ISSUE TITLE
nested query support

### ISSUE THREAD

**Issue by rezoan** [scale-tone/linq2dynamodb#44]
> Seems there is no support of nested object property query.

For Example if i have an **object** :
```
{
    Id: 206,
    Title: "20-Bicycle 206",
    Description: "206 description",
    RelatedItems: [
        341, 
        472, 
        649
    ],
    Pictures: {
        FrontView: "123", 
        RearView: "456",
        SideView: "789"
    }
}
```

i can't query using Picture.FrontView:

`this.Context.GetTable<BiCycle>().FirstOrDefault(x => x.Pictures.FrontView == "123");`

Any help would be highly appreciated.

**Comment by scale-tone** [comment]
Yes, I'm afraid, you cannot send such a request to DynamoDB (because obviously DynamoDB doesn't support that). 
Though you can do it on the client side:
`this.Context.GetTable<BiCycle>().ToList().FirstOrDefault(x => x.Pictures.FrontView == "123");
`
(beware of accidentally requesting the contents of the whole table!)

Or you could try to achieve what you need with [a custom filter expression](https://github.com/scale-tone/linq2dynamodb/blob/master/Sources/Linq2DynamoDb.DataContext/DataContextExtensions.cs#L61).
