### ISSUE TITLE
Unable to cast object of type xxx to type 'Amazon.DynamoDBv2.DocumentModel.Primitive'

### ISSUE THREAD

**Issue by sawsonh** [scale-tone/linq2dynamodb#57]
I am receiving this error.  This occur on a class property that was defined of type 'object' but during run-time I cast it to of type xxx.  I have no issues with respect to the casting - I see my object correctly updated in inspection.  However, I am not able to write my updated object to DynamoDB because of the error mentioned.
Any ideas?

**Comment by scale-tone** [comment]
Hello sawsonh,

Fields of type 'object' are not supported out-of-the-box. All fields have to be strongly-typed (otherwise Linq2DynamoDb won't be able to auto-generate serialization/deserialization code for them).

Alternatively, you can define [your custom IPropertyConverter](https://github.com/scale-tone/linq2dynamodb/wiki/Defining-Entities) for your field.
