### ISSUE TITLE
Query not evaluating correctly executes as a scan.

### ISSUE THREAD

**Issue by jpshipp** [scale-tone/linq2dynamodb#61]
I have a Table with a GSI and I have a function like this. 

public virtual IQueryable<T> All(Func<T, bool> expression)
{
            if (expression == null) return All();

            return _table.Where(expression).AsQueryable();
 }

The expression I hand into the function looks like this 

l => l.GSIVariable == someValue && l.CreatedDate > DateTime.Now.AddDays(-7))

Do I have to modify the function or expression to make this correctly call a query on dynamoDB?

I am using the onlog Action to debug that the table is executing as a scan SELECT * FROM TableName.

To me it looks like it is getting the whole table then evaluating the query on the table after the table has been scanned.

**Comment by scale-tone** [comment]
Hello, @jpshipp , what you hand into the function is a [delegate](https://docs.microsoft.com/en-us/dotnet/api/system.func-2?view=netframework-4.8) instance (in C# it is an equivalent to function pointers in e.g. C++). At runtime, it's nothing more than a pointer, so LINQ2DynamoDB can only invoke the default logic (which is retrieving the entire table) and then apply that delegate to each returned item.

LINQ2DynamoDB's magic of converting code into queries relies on [Expressions](https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.expression?view=netframework-4.8), of which you can think as of a piece of code compiled lazily and on demand (and maybe even not compiled). When given an Expression, LINQ2DynamoDB parses it and does its best to convert it into DynamoDB query. 

That said, if you change your method's definition to

``
public virtual IQueryable All(Expression<Func<T, bool>> expression)
``

that would most likely produce the results that you expect. And in that case you could also omit the .AsQueryable() ending, as it will be redundant. 

At the same time, check if you really want to return an IQueryable from your method (It sounds a bit strange from code design perspective, because if your intention is to encapsulate all the query logic inside your class, then you would rather return an IEnumerable. While if you want to allow your clients to apply their own arbitrary custom queries, then why would you need a method like the above?...).

Hope it helps.

**Comment by jpshipp** [comment]
Yes that helps heaps everything is working well now. I will take a look at the design of the code this is a project I have taken over from someone else so there might be intention behind it I am not seeing but you make a good point. Thank you for the quick and very helpful reply.
