### ISSUE TITLE
System.NotSupportedException: 'The binary operator 'Or' is not supported'

### ISSUE THREAD

**Issue by felipesotero** [scale-tone/linq2dynamodb#62]
Hello all. I'm trying to do a simple query using my test table in DynamoDB. But for any OR query I'm getting the `System.NotSupportedException: 'The binary operator 'Or' is not supported'`. The same applies to OrElse.

 Maybe I'm missing some premise in dealing with constraints in DynamoDB or even Linq in C#.

Here's the code:
```c#
// The Entity
    [DynamoDBTable("TbRelacionamento")]
    public class TbRelacionamento
    {
        [DynamoDBHashKey]
        public string ID { get; set; }
        // Some other unimportant attributes in between

        // In between the attributes we have Enums 
        public RelacionamentoFgStatusEnum FgStatus { get; set; }

        public bool? Reservado { get; set; } // This is the attribute to be queried for

        // In between the attributes we have DateTimes 
        public DateTime DataEnvioAgendamento { get; set; }

        // And also simple objects
        public List<ProdutoCarrinho> Produtos { get; set; }
    }
```

Here are the test that breaks with the given exception above
```c#
var test2 = context.TbRelacionamentos.Where(x => x.Reservado == false | x.Reservado == null);
var test3 = test2.Take(Limit).ToList();
var test = (from relationship in context.GetTable<TbRelacionamento>()
            where relationship.Reservado == false || relationship.Reservado == null
            select relationship).Take(Limit).ToList();
```

Is there anything I'm missing?

**Comment by scale-tone** [comment]
@felipesotero , the binary operator 'Or' is not supported, because [it is not supported by DynamoDB](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/DynamoDBv2/TScanOperator.html).

Generally, what I could recommend in such cases is to make two separate queries and then [.Union()](https://docs.microsoft.com/en-us/dotnet/api/system.linq.enumerable.union?view=netframework-4.8) them.
But in your case it should be way much simpler: you just do `.Where(x => x.Reservado != true)` instead.
